ReadSpeaker.pub||(ReadSpeaker.pub={});
ReadSpeaker.pub.Config=function(){var e={extraMods:[],general:{cookieLifetime:36E7,cookieName:"ReadSpeakerSettings",cookieDomain:null,cookiePath:"/",domain:"readspeaker.com",popupCloseTime:2E3,protocol:document.location.protocol||"http:",proxyVersion:"2",region:"eu",rscall:null,rsent:"rsent",subdomain:"app",syncContainer:"default",selectionEngine:"old",useCompactPopupButton:!0,usePost:!1,sentOnlyLang:["ja_jp","zh_cn"],popupHref:"",parseMathJax:!1,enableSkipAlways:!1},survey:{allowed:!1,url:function(){return e.general.protocol+
"//f1-eu.readspeaker.com/survey/survey.php"},cookieName:"rspkrsurvey",cookieLifeTime:15552E6},settings:{hltoggle:"hlon",hl:"wordsent",hlicon:"iconon",hlspeed:"medium",hlword:"#a4cbff",hlsent:"#beffd6",hlscroll:"scrolloff",hltext:"#000000"},defaultsettings:{hltoggle:"hlon",hl:"wordsent",hlicon:"iconon",hlspeed:"medium",hlword:"#a4cbff",hlsent:"#beffd6",hlscroll:"scrolloff",hltext:"#000000"},phrases:{

fr_fr:{listen:"Ecoutez",closeplayer:"Fermez le lecteur",fast:"Rapide",hide:"Cacher",highlightingoptions:"Options de surbrillance",listentoselectedtext:decodeURIComponent("Ecouter le texte s%C3%A9lectionn%C3%A9"),medium:"Moyen",nohighlighting:"Pas de surbrillance",pause:"Pause",playerwidth:"305",play:"Lecture",popupbutton:"Bouton popup",sentonly:"Phrase uniquement",settings:"Param&egrave;tres",show:"Montrer",slow:"Lent",speechenabled:'Vocalis&eacute; par <a href="http://www.readspeaker.com/fr/?ref='+
encodeURIComponent(document.location.href)+'" target="_blank">ReadSpeaker</a>',newwindow:decodeURIComponent("Nouvelle%20fen%C3%AAtre"),speed:"Vitesse",stop:"Stop",volume:"Volume",wordonly:"Mot uniquement",wordsent:"Mot et phrase",nosound:"Aucun son? Cliquez ici",download:decodeURIComponent("T%C3%A9l%C3%A9chargez mp3"),highlighting:"Surbrillance",wordcolor:"Coloris des mots",sentcolor:"Coloris des phrases",lightgreen:"Vert clair",lightblue:"Bleu clair",lightyellow:"Jaune clair",white:"Blanc",black:"Noir",
underline:decodeURIComponent("Soulign%C3%A9"),none:"Aucun",on:decodeURIComponent("Activ%C3%A9"),off:decodeURIComponent("D%C3%A9sactiv%C3%A9"),autoscroll:decodeURIComponent("D%C3%A9filement automatique"),general:decodeURIComponent("G%C3%A9n%C3%A9ral"),reading:"Lecture",showhighlighting:"Surbrillance du texte",help:"Aide",hltoggleinfo:decodeURIComponent("Active%20la%20surbrillance%20synchronis%C3%A9e%20du%20texte%20qui%20est%20en%20train%20d%27%C3%AAtre%20lu."),hloptionsinfo:decodeURIComponent("Contr%C3%B4le le type de subrillance synchronis%C3%A9e."),
hlwordinfo:decodeURIComponent("Active le style ou la couleur des mots surbrill%C3%A9s."),hlsentinfo:decodeURIComponent("Active le style ou la couleur des phrases surbrill%C3%A9es."),hltextinfo:decodeURIComponent("D%C3%A9finit%20la%20couleur%20de%20premier%20plan%20pour%20le%20texte%20en%20surbrillance."),hlspeedinfo:decodeURIComponent("Contr%C3%B4le la vitesse de lecture."),hlscrollinfo:decodeURIComponent("Basculement du d%C3%A9filement automatique. Quand activ%C3%A9, la page d%C3%A9filera automatiquement pour accompagner le texte surbrill%C3%A9."),
hliconinfo:decodeURIComponent("Contr%C3%B4le%20si%20un%20mini%20lecteur%20doit%20%C3%AAtre%20affich%C3%A9%20ou%20pas%20quand%20le%20texte%20est%20s%C3%A9lectionn%C3%A9."),close:"Fermer",sliderseek:"Curseur de position",slidervolume:"Barre du volume",slidervolumedesc:"Modifier le volume",touheading:decodeURIComponent("Conditions d'utilisation pour le t%C3%A9l%C3%A9chargement de l'audio"),toubody:decodeURIComponent("%3Cp%3EMerci%20d%27avoir%20utilis%C3%A9%20le%20service%20ReadSpeaker%3C%2Fp%3E%3Cp%3ELe%20fichier%20audio%20que%20vous%20%C3%AAtes%20sur%20le%20point%20de%20t%C3%A9l%C3%A9charger%20est%20pour%20votre%20usage%20personnel%20uniquement.%20Vous%20ne%20pouvez%20pas%20le%20distribuer%2C%20une%20autre%20personne%2C%20ou%20l%27utiliser%2C%20d%27autre%20fins%2C%20autrement%20que%20pour%20un%20usage%20personnel.%3C%2Fp%3E"),
touaccept:decodeURIComponent("Accepter et T%C3%A9l%C3%A9charger le fichier"),toudecline:"Annuler",textcolor:"Couleur du texte",darkred:decodeURIComponent("Rouge%20fonc%C3%A9"),darkgreen:decodeURIComponent("Vert%20fonc%C3%A9"),darkblue:decodeURIComponent("Bleu%20fonc%C3%A9"),yellow:"Jaune",loaderror:"Erreur, essayez de nouveau",hlrestore:decodeURIComponent("Restaurer%20param%C3%A8tres%20d%27origine"),hlrestoreinfo:decodeURIComponent("Restaurer%20tous%20les%20param%C3%A8tres%20%C3%A0%20leurs%20valeurs%20d%27origine."),
red:"Rouge",chunkbutton:"Continuez",chunkcontinue:decodeURIComponent("Cliquez%20sur%20le%20bouton%20continuer%20pour%20continuer%20la%20lecture."),chunkwait:decodeURIComponent("Merci%20d%27attendre.%20La%20lecture%20continuera%20sous%20peu.")}
,
pt_pt:{listen:"Ouvir",closeplayer:"Fechar Janela",fast:"R&aacute;pida",hide:"Esconder",highlightingoptions:"Op&ccedil;&otilde;es de contraste",listentoselectedtext:"Ouvir o texto seleccionado",medium:"M&eacute;dia",nohighlighting:"Sem contraste",pause:"Pausa",playerwidth:"375",play:"Play",popupbutton:"Janela de Pop up",sentonly:"Apenas a frase",settings:"Configura&ccedil;&otilde;es",show:"Mostrar",slow:"Lenta",speechenabled:'Vocalizado por <a href="http://www.readspeaker.com/pt/?ref='+encodeURIComponent(document.location.href)+
'" target="_blank">ReadSpeaker</a>',newwindow:"Nova janela",speed:"Velocidade",stop:"Parar",volume:"Volume",wordonly:"Apenas a palavra",wordsent:"Palavra e frase",nosound:"N&atilde;o consegue ouvir? Clique aqui",download:"Descarregar mp3",highlighting:"Destaque",wordcolor:"Cor da palavra",sentcolor:"Cor da frase",lightgreen:"Verde luminoso",lightblue:"Azul luminoso",lightyellow:"Amarelo luminoso",white:"Branco",black:"Preto",underline:"Sublinhado",none:"Nenhum",on:"Ligado",off:"Desligado",autoscroll:decodeURIComponent("Scroll autom%C3%A1tico"),
general:"Geral",reading:"Leitura",showhighlighting:"Destaque do texto",help:"Ajuda",hltoggleinfo:decodeURIComponent("Permite fazer o destaque do texto em simult%C3%A2neo com a sua leitura."),hloptionsinfo:decodeURIComponent("Controla o comportamento do destaque simult%C3%A2neo."),hlwordinfo:"Define o estilo ou a cor das palavras em destaque.",hlsentinfo:"Define o estilo ou a cor das frases em destaque.",hlspeedinfo:"Controla a velocidade de leitura.",hlscrollinfo:decodeURIComponent("Activa%20o%20scroll%20autom%C3%A1tico.%20Quando%20ligado%2C%20a%20p%C3%A1gina%20entra%20em%20scroll%20autom%C3%A1tico%20para%20acompanhar%20o%20destaque%20do%20texto."),
hliconinfo:decodeURIComponent("Controla se deve ou n%C3%A3o surgir um mini player quando %C5%BD seleccionado texto."),close:"Fechar",sliderseek:"Barra de busca",slidervolume:"Barra de volume de som",slidervolumedesc:"Alterar volume de som",touheading:decodeURIComponent("Termos de uso para o %C3%A1udio descarregado"),toubody:decodeURIComponent("<p>Obrigado por usar o servi%C3%A7o ReadSpeaker.</p><p>O ficheiro de %C3%A1udio que est%C3%A1 prestes a descarregar %C3%A9 apenas para o seu uso pessoal. Isto significa que n%C3%A3o lhe %C3%A9 permitido distribuir o ficheiro por outras pessoas, ou us%C3%A1-lo para outro prop%C3%B3sito que n%C3%A3o seja o de o ouvir.</p>"),
touaccept:"Aceitar e Descarregar o ficheiro",toudecline:"Cancelar",textcolor:"Cor do texto",hltextinfo:"Define a cor das palavras em destaque",darkred:"Vermelho-escuro",darkgreen:"Verde-escuro",darkblue:"Azul-escuro",yellow:"Amarelo",loaderror:"Ocorreu um erro, tente outra vez",hlrestore:"Repor valores de origem",hlrestoreinfo:decodeURIComponent("Repor%20valores%20de%20origem%20para%20todas%20as%20configura%C3%A7%C3%B5es."),red:"Vermelho",chunkbutton:"Continuar",chunkcontinue:decodeURIComponent("Prima%20o%20bot%C3%A3o%20Continuar%20para%20prosseguir%20a%20leitura"),
chunkwait:decodeURIComponent("Por%20favor%2C%20espere.%20A%20leitura%20prosseguir%C3%A1%20em%20breve.")}
,
es_es:{listen:"Escuchar",closeplayer:"Cerrar reproductor",fast:"Alta",hide:"Esconder",highlightingoptions:"Opciones de resaltado",listentoselectedtext:"Escuchar al texto seleccionado",medium:"Media",nohighlighting:"Sin resaltar",pause:"Pausa",playerwidth:"345",play:"Reproducir",popupbutton:"Bot&oacute;n emergente",sentonly:"Frase solamente",settings:"Preferencias",show:"Mostrar",slow:"Baja",speechenabled:'Vocalizado por <a href="http://www.readspeaker.com/es/?ref='+encodeURIComponent(document.location.href)+
'" target="_blank">ReadSpeaker</a>',newwindow:"Nueva ventana",speed:"Velocidad",stop:"Parar",volume:"Volumen",wordonly:"Palabra solamente",wordsent:"Palabra y frase",nosound:decodeURIComponent("%C2%BFNo%20hay%20sonido%3F%20Pulse%20aqu%C3%AD"),download:"Descargar mp3",highlighting:"Efecto resaltado",wordcolor:"Color de las palabras",sentcolor:"Color de las frases",lightgreen:"Verde claro",lightblue:"Azul claro",lightyellow:"Amarillo claro",white:"Blanco",black:"Negro",darkred:"Rojo oscuro",darkgreen:"Verde oscuro",
darkblue:"Azul oscuro",yellow:"Amarillo",underline:"Subrayado",none:"Ninguno",on:"Activado",off:"Desactivado",autoscroll:decodeURIComponent("Desplazamiento%20vertical%20(scroll)%20autom%C3%A1tico"),general:"General",reading:"Lectura",showhighlighting:"Efecto resaltado en el texto",help:"Ayuda",hltoggleinfo:decodeURIComponent("Habilita%20el%20efecto%20resaltado%20del%20texto%20que%20se%20est%C3%A1%20leyendo."),hloptionsinfo:"Controla el comportamiento del efecto resaltado sincronizado con la lectura.",
hlwordinfo:"Ajusta el estilo o color del efecto resaltado en las palabras.",hlsentinfo:"Ajusta el estilo o color del efecto resaltado en las frases.",hlspeedinfo:"Controla la velocidad de lectura.",hlscrollinfo:decodeURIComponent("Activa%20el%20desplazamiento%20vertical%20autom%C3%A1tico.%20Activado%2C%20la%20p%C3%A1gina%20se%20desplaza%20verticalmente%20de%20manera%20autom%C3%A1tica%20para%20seguir%20al%20efecto%20resaltado%20del%20texto."),hliconinfo:decodeURIComponent("Controla%20si%20el%20minireproductor%20se%20mostrar%C3%A1%20cuando%20se%20selecciona%20texto."),
close:"Cerrar",sliderseek:decodeURIComponent("Control%20de%20tiempo%20de%20reproducci%C3%B3n"),slidervolume:"Control de volumen",slidervolumedesc:"Cambiar volumen",touheading:"Condiciones de uso para la descarga de archivos de audio.",toubody:decodeURIComponent("%3Cp%3EGracias%20por%20usar%20el%20servicio%20ReadSpeaker.%3C%2Fp%3E%3Cp%3ESolo%20se%20permite%20utilizar%20el%20archivo%20de%20audio%20que%20va%20a%20descargar%20para%20uso%20personal.%20Esto%20significa%20que%20no%20est%C3%A1%20permitida%20la%20distribuci%C3%B3n%20de%20este%20archivo%20de%20audio%20con%20otras%20personas%2C%20o%20su%20uso%20para%20cualquier%20otro%20prop%C3%B3sito%20diferente%20a%20escucharlo%20usted%20personalmente.%3C%2Fp%3E"),
touaccept:"Aceptar y descargar el archivo de audio",toudecline:"Cancelar",textcolor:"Color del texto",hltextinfo:"Establece el color de fondo del texto seleccionado",loaderror:"Se ha producido un error",hltextinfo:"Restaurar los valores predeterminados",loaderror:"Restaurar todos los ajustes a sus valores originales.",hlrestore:"Restaurar los valores predeterminados",hlrestoreinfo:"Restaurar todos los ajustes a sus valores originales.",red:"Rojo",chunkbutton:"Continuar",chunkcontinue:decodeURIComponent("Haga%20clic%20en%20el%20bot%C3%B3n%20continuar%20para%20continuar%20la%20lectura."),
chunkwait:decodeURIComponent("Por%20favor%20espere.%20%20La%20lectura%20continuar%C3%A1%20en%20breve.")}
,
en_uk:{listen:"Listen",closeplayer:"Close Player",fast:"Fast",hide:"Hide",highlightingoptions:"Highlighting options",listentoselectedtext:"Listen to selected text",medium:"Medium",nohighlighting:"No highlighting",pause:"Pause",playerwidth:"310",play:"Play",popupbutton:"Pop-up button",sentonly:"Sentence only",settings:"Settings",show:"Show",slow:"Slow",speechenabled:'Speech-enabled by <a href="http://www.readspeaker.com/?ref='+encodeURIComponent(document.location.href)+'" target="_blank">ReadSpeaker</a>',
newwindow:"New Window",speed:"Speed",stop:"Stop",volume:"Volume",wordonly:"Word only",wordsent:"Word and sentence",nosound:"No sound? Click here",download:"Download mp3",highlighting:"Highlighting",wordcolor:"Word colour",sentcolor:"Sentence colour",lightgreen:"Light green",lightblue:"Light blue",lightyellow:"Light yellow",white:"White",black:"Black",darkred:"Dark red",darkgreen:"Dark green",darkblue:"Dark blue",yellow:"Yellow",underline:"Underline",none:"None",on:"On",off:"Off",autoscroll:"Automatic scrolling",
general:"General",reading:"Reading",showhighlighting:"Text highlighting",help:"Help",hltoggleinfo:"Enables synchronised highlighting of the text that is currently being read.",hloptionsinfo:"Controls the behaviour of synchronised highlighting.",hlwordinfo:"Sets the style or colour of highlighted words.",hlsentinfo:"Sets the style or colour of highlighted sentences.",hltextinfo:"Sets the foreground colour of the highlighted text.",hlspeedinfo:"Controls the reading speed.",hlscrollinfo:"Toggles automatic scrolling. When switched on, the page will automatically scroll to follow the highlighted text.",
hliconinfo:"Controls whether or not a pop-up button should be displayed when text is selected.",close:"Close",sliderseek:"Seek bar",slidervolume:"Volume bar",slidervolumedesc:"Change volume",touheading:"Terms of use for downloaded audio",toubody:"<p>Thank you for using the ReadSpeaker service.</p><p>The audio file you are about to download can be used for personal use only. This means that you are not allowed to distribute this file to anyone else, or use it for any other purpose than to listen to it yourself.</p>",
touaccept:"Agree and Download file",toudecline:"Cancel",textcolor:"Text colour",loaderror:"An error has occurred, try again",hlrestore:"Restore default settings",hlrestoreinfo:"Restore all settings to their original defaults.",red:"Red",chunkbutton:"Continue",chunkcontinue:"Click the \u201ccontinue\u201d button to continue the reading.",chunkwait:"Please wait. The reading will continue shortly."}},ui:{rsbtnClass:"rsbtn",progressHandleClass:"rsbtn_progress_handle rsimg",progressDir:"h",volumeHandleClass:"rsbtn_volume_handle rsimg",volumeDir:"v",autoscrollOffset:0,usePin:!1,settingsListenButton:!0,listenBtn:'<div id="readspeaker_button_settings" class="rs_skip rsbtn rs_preserve readspeaker_button_settings">;\t<a class="rsbtn_play" href="">;\t\t<span class="rsbtn_left rsimg rspart">;\t\t\t<span class="rsbtn_text">;\t\t\t\t<span>rsLISTENrs</span>;\t\t\t</span>;\t\t</span>;\t\t<span class="rsbtn_right rsimg rsplay rspart"></span>;\t</a>;</div>'.split(";"),
player:'<a class="rsbtn_pause rsimg rspart" href="javascript:void(0);" title="Pause" role="button"><span class="rsbtn_btnlabel">Pause</span></a>,<a class="rsbtn_stop rsimg rspart" href="javascript:void(0);" title="Stop" role="button"><span class="rsbtn_btnlabel">Stop</span></a>,<span class="rsbtn_player rsimg rspart">,\t<span class="rsbtn_progress_container rsimg rsplaypart rsloading">,\t\t<span class="rsbtn_progress_played rsimg"></span>,\t</span>\t,\t<a class="rsbtn_volume rsimg rsplaypart" href="javascript:void(0);" title="Volume" role="button"><span class="rsbtn_btnlabel">Volume</span></a>,\t<span class="rsbtn_volume_container rsimg">,\t\t<span class="rsbtn_volume_slider"></span>,\t</span>,\t<a class="rsbtn_settings rsimg rsplaypart" href="javascript:void(0);" title="Settings" role="button"><span class="rsbtn_btnlabel">Settings</span></a>,\t<a class="rsbtn_dl rsimg rsplaypart" href="javascript:void(0);" title="Download MP3" role="button"><span class="rsbtn_btnlabel">Download mp3</span></a>,\t<a class="rsbtn_pin turnedOff rsplaypart" href="javascript:void(0);" title="Pin player" role="button"><span class="rsbtn_btnlabel">Pin player</span></a>,</span>,<a class="rsbtn_closer rsimg rspart" href="javascript:void(0);" title="Close Player" role="button"><span class="rsbtn_btnlabel">Close</span></a>,<span class="rsbtn_powered rsimg"><span class="rsbtn_btnlabel">Speech-enabled by ReadSpeaker</span></span>'.split(","),
popupbutton:['<a class="rsbtn_play" accesskey="L" title="" href="">','<span class="rsbtn_left rsimg rspart"><span class="rsbtn_text"><span></span></span></span>','<span class="rsbtn_right rsimg rsplay rspart"></span>',"</a>"],popupplayer:function(){return this.player},settings:{form:'<div id="rsform_wrapper" dir="ltr">;\t<h1 class="rs_preserve">rsSETTINGS_HEADINGrs</h1>;\trsLISTEN_BUTTONrs;\t<form id="rssettings_form" class="rsform rs_preserve">;\trsSECTIONS_STARTrs;\trsSECTIONSrs;\trsSECTIONS_ENDrs;\t</form>;</div>'.split(";"),
formsection:['<fieldset id="rsSECTION_IDrs" class="rsform-section">',"\t<legend>rsSECTION_HEADINGrs</legend>","\trsSECTION_ROWSrs","</fieldset>"],formrow:['\t<div class="rsform-row rsCONTROL_CLASSESrs" id="rscontrol_rsCONTROL_IDrs" data-rsform-type="rsCONTROL_TYPErs">',"\t\trsCONTROLrs","\t</div>"],formbuttons:['\t\t<a class="rssettings-button-close rsdialog-button" href="javascript:void(0);" title="rsSETTINGS_BUTTON_CLOSErs" role="button">rsSETTINGS_BUTTON_CLOSErs</a>']},overlay:{overlayStyles:"position: absolute;top: 0;left: 0;bottom: 0;width: 100%;background-color: #fff;opacity: 0.5;filter: alpha(opacity=50);z-index: 1001".split(";"),
contentStyles:"position: absolute;width: 500px;height: 500px;background-color: #eee;z-index: 10002;border-radius: 10px;-moz-box-shadow: 0px 0px 20px #000;-webkit-box-shadow: 0px 0px 20px #000;box-shadow: 0px 0px 20px #000;display: block".split(";"),contentTemplate:'<div id="rslightbox_content" style="overflow:auto;"></div>,<div id="rslightbox_toolbar">,\t<a id="rslightbox_closer" href="javascript: void(0);" title="rsLIGHTBOX_CLOSE_LABELrs" role="button"><span class="rsbtn_btnlabel">rsLIGHTBOX_CLOSE_LABELrs</span></a>,</div>,<div id="rslightbox_buttons" class="rsform-buttons"></div>,<div id="rslightbox_logo" class="rsimg"></div>'.split(",")},
dldialog:'<div id="rsdl_container">;\t<div class="rsdl_textwrapper">;\t\t<h2>rsTERMS_OF_USE_HEADINGrs</h2>;\t\trsTERMS_OF_USE_BODYrs;\t</div>;</div>'.split(";"),dlbuttons:['\t\t<a id="rsdl_button_accept" class="rsdialog-button" href="javascript:void(0);" title="rsTERMS_OF_USE_ACCEPTrs" role="button">rsTERMS_OF_USE_ACCEPTrs</a>','\t\t<a id="rsdl_button_decline" class="rsdialog-button" href="javascript:void(0);" title="rsTERMS_OF_USE_DECLINErs" role="button">rsTERMS_OF_USE_DECLINErs</a>'],survey:{buttons:['\t\t<a id="rssurvey_button_close" class="rsdialog-button" href="javascript:void(0);" title="rsSURVEY_BUTTON_CLOSErs" role="button">rsSURVEY_BUTTON_CLOSErs</a>']}},
flash:{allowScriptAccess:"always",flashSrc:function(){var a=e.general.protocol+"//f1-"+e.general.region+".readspeaker.com/flash/readspeaker_1x1.swf";return rs.cfg.item("general.customProxy")?rs.cfg.item("general.customProxy")+encodeURIComponent(a):a}},cb:{ui:{open:function(){rspkr.log("conf.cb.ui.open: "+this)},play:function(){rspkr.log("conf.cb.ui.play")},pause:function(){rspkr.log("conf.cb.ui.pause")},stop:function(){rspkr.log("conf.cb.ui.stop")},beforeclose:function(){rspkr.log("conf.cb.ui.beforeclose")},
close:function(){rspkr.log("conf.cb.ui.close")},settingsopened:function(){rspkr.log(this)},volumechanged:function(a){rspkr.log("conf.cb.ui.volumechanged: "+a+"%")},timeupdated:function(){},progresschanged:function(a){0<a&&0==a%10&&rspkr.log("conf.cb.ui.progresschanged: "+a+"%")}},chunking:{pause:void 0}}},h={highlighting:{phrase:"ph_highlighting",items:{hltoggle:{phrase:"ph_showhighlighting",type:"radio",info:"ph_hltoggleinfo",options:[{value:"hlon",phrase:"ph_on"},{value:"hloff",phrase:"ph_off",
dims:["hl","hlword","hlsent","hltext","enlarge"]}]},hl:{phrase:"ph_highlightingoptions",type:"select",info:"ph_hloptionsinfo",options:[{value:"wordsent",phrase:"ph_wordsent"},{value:"sent",phrase:"ph_sentonly",dims:["hlword"]},{value:"word",phrase:"ph_wordonly",dims:["hlsent"]},{value:"none",phrase:"ph_nohighlighting",dims:["hlword","hlsent","hltext"]}]},hlword:{phrase:"ph_wordcolor",type:"colorpicker",info:"ph_hlwordinfo",options:[{value:"#beffd6",phrase:"ph_lightgreen"},{value:"#a4cbff",phrase:"ph_lightblue"},
{value:"#ffffcc",phrase:"ph_lightyellow"},{value:"#ffffff",phrase:"ph_white"},{value:"#000000",phrase:"ph_black"},{value:"#770000",phrase:"ph_darkred"},{value:"#ED0000",phrase:"ph_red"},{value:"underline",phrase:"ph_underline"},{value:"none",phrase:"ph_none"}]},hlsent:{phrase:"ph_sentcolor",type:"colorpicker",info:"ph_hlsentinfo",options:[{value:"#beffd6",phrase:"ph_lightgreen"},{value:"#a4cbff",phrase:"ph_lightblue"},{value:"#ffffcc",phrase:"ph_lightyellow"},{value:"#ffffff",phrase:"ph_white"},{value:"#000000",
phrase:"ph_black"},{value:"#770000",phrase:"ph_darkred"},{value:"#ED0000",phrase:"ph_red"},{value:"underline",phrase:"ph_underline"},{value:"none",phrase:"ph_none"}]},hltext:{phrase:"ph_textcolor",type:"colorpicker",info:"ph_hltextinfo",options:[{value:"#003f00",phrase:"ph_darkgreen"},{value:"#0000aa",phrase:"ph_darkblue"},{value:"#ffff00",phrase:"ph_yellow"},{value:"#ffffff",phrase:"ph_white"},{value:"#000000",phrase:"ph_black"},{value:"#a4cbff",phrase:"ph_lightblue"}]}}},reading:{phrase:"ph_reading",
items:{hlspeed:{phrase:"ph_speed",type:"radio",info:"ph_hlspeedinfo",options:[{value:"slow",phrase:"ph_slow"},{value:"medium",phrase:"ph_medium"},{value:"fast",phrase:"ph_fast"}]}}},general:{phrase:"ph_general",items:{hlscroll:{phrase:"ph_autoscroll",type:"radio",info:"ph_hlscrollinfo",options:[{value:"scrollon",phrase:"ph_on"},{value:"scrolloff",phrase:"ph_off"}]},hlicon:{phrase:"ph_popupbutton",type:"radio",info:"ph_hliconinfo",options:[{value:"iconon",phrase:"ph_on"},{value:"iconoff",phrase:"ph_off"}]}}},
restore:{phrase:"ph_hlrestore",items:{hlrestore:{phrase:"ph_hlrestoreinfo",type:"restore"}}}},g=function(a,b,c,d){if(void 0!==a[b[c]])return c<b.length-1?g(a[b[c]],b,c+1,d):void 0===d?a[b[c]]:a[b[c]]=d;if(void 0!==d){var e;if(c<b.length-1)for(e=b.length;c<e-1;c++)a[b[c]]={},a=a[b[c]];return a[b[c]]=d}},f=function(a,b){b=b||e;for(var c in a)a.hasOwnProperty(c)&&(void 0!==b[c]?$rs.isArray(b[c])?b[c]=a[c]:"object"==typeof a[c]&&0<Object.size(a[c])&&!$rs.isArray(a[c])?f(a[c],b[c]):b[c]=a[c]:b[c]=a[c])};
return{meta:{revision:"4926"},defaultsettings:e.defaultsettings,init:function(){rspkr.log("[rspkr.cfg] Initialized!")},item:function(a,b,c){if(void 0===b){if("."==a)b=e;else if(b=a.split("."),a=g(e,b,0),"function"!=typeof a||c)b=a;else{var d=e;c=e;if(b.length){b.splice(b.length-1,1);for(var d=0,f=b.length;d<f;d++)if(c[b[d]])c=c[b[d]];else break;d=c}b=a.apply(d)}return b}a=a.split(".");return g(e,a,0,b)},getPhrase:function(a,b,c){c=c||"en_us";b=(b||rspkr.c.data.params.lang||c).toLowerCase();var d=
this.item("phrases."+b);if(d&&d[a])return this.item("phrases."+b)[a];if(this.item("phrases."+c+"."+a))return this.item("phrases."+c+"."+a)},getPhrases:function(a,b){b=b||"en_us";var c;if((c=this.item("phrases."+(a||b).toLowerCase()))||(c=this.item("phrases."+b)))return c},extendPhrases:function(a){for(var b in a)this.item("phrases."+b)||delete a[b];f({phrases:a})},getSettingsConf:function(){return h},isSentOnly:function(a){for(var b=this.item("general.sentOnlyLang")||[],c=0,d=b.length;c<d;c++)if(a&&
b[c]==a.toLowerCase())return!0;return!1},setup:function(){"object"==typeof window.rsConf&&f(window.rsConf);rspkr.devt("onConfigSetup",window)},execCallback:function(a,b,c){"function"==typeof this.item(a,void 0,!0)&&this.item(a,void 0,!0).apply(b,$rs.isArray(c)?c:[])},c:e}}();
